name: Flutter CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
          channel: 'stable'
          cache: true
      - run: flutter pub get
      #- run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - run: flutter build apk
      - run: flutter build web --release

      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      - uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: build/web

  deploy:
    name: Deploy Web Build
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Download Web Release
      uses: actions/download-artifact@v2
      with:
        name: github-pages

    - name: Deploy to github pages
      id: deployment
      uses: actions/deploy-pages@v2

    #- name: Deploy to gh-pages
    #  uses: peaceiris/actions-gh-pages@v3
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}
    #    publish_dir: ./