name: Flutter CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
          channel: 'stable'
          cache: true
      - run: flutter pub get
      #- run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - run: flutter build apk
      - run: flutter build web --release

      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      - uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: build/web
  
      - name: Firebase Deploy live web app
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_EXSAE_TECHNOLOGIES }}'
          channelId: live
          projectId: exsae-technologies
      
      - name: Firebase App Distribution
        uses: hasretsariyer/firebase-app-distribution-github-action@main
        with:
          app_id: ${{secrets.FIREBASE_APP_ID}}
          firebase_token: ${{secrets.FIREBASE_TOKEN}}
          app_file: build/app/outputs/apk/release/app-release.apk
          tester_groups: maintainers
